# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-25 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puissance4', '0002_auto_20200325_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='turn',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
