# Generated by Django 2.2.7 on 2020-03-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puissance4', '0003_game_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='fini',
            field=models.BooleanField(default=True),
        ),
    ]
