# Generated by Django 2.2.7 on 2020-03-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puissance4', '0004_game_fini'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='fini',
            field=models.BooleanField(default=False),
        ),
    ]
